blog/groups/routes.py
from flask import Blueprint,render_template


groups = Blueprint('groups', __name__)


@groups.route('/groups')
def groups_page():
    return render_template('groups/groups.html')

blog/main/routes.py
from flask import Blueprint

from flask import Flask, render_template, request

from blog.models import User, Post

from flask_login import  login_required


main = Blueprint('main', __name__)


@main.route('/articles')
@login_required
def article_page():
    page = request.args.get('page', 1, type=int)
    posts = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
    return render_template('post_templates/articles.html', posts=posts)


@main.route('/')
@main.route('/home')
def home_page():
    return render_template('home.html')

@main.route('/pythonrepl')
def python_repl():
    return render_template('python_repl/python_repl.html')

blog/posts/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, abort, request

from blog.posts.forms import PostForm, SearchForm
from blog.models import Post
from blog import db
from flask_login import login_required, current_user

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        flash('Your post has been created', 'success')
        post = Post(title=form.title.data, content=form.content.data, owner=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.article_page'))
    return render_template('post_templates/create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post_templates/post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if post.author != current_user:
        abort(403)

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('post_templates/create_post.html', title='Update Post', form=form, legend='Update post')


@posts.route('/post/search', methods=['POST'])
@login_required
def search_engine():
    form = SearchForm()

    if form.validate_on_submit():
        # post_searched = form.searched.data
        page = request.args.get('page', 1, type=int)
        posts1 = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        return render_template('post_templates/articles.html', posts=posts1)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def post_delete(post_id):
    post1 = Post.query.get_or_404(post_id)
    if post1.author != current_user:
        abort(403)

    db.session.delete(post1)
    db.session.commit()
    flash('You post has been deleted', 'success')

    return redirect(url_for('main.article_page'))

blog/users/routes.py
from flask import Flask, render_template, redirect, url_for, flash, request

from blog.users.forms import RegisterForm, LoginForm, UpdateProfileForm, ResetForm, ResetPasswordForm
from blog.models import User, Post
from blog import db
from flask_login import login_user, logout_user, login_required, current_user
import secrets
import os
from flask_mail import Message
from flask import Blueprint, current_app

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(username=form.username.data, email=form.email.data, passwordHash=form.password1.data)
        db.session.add(user_to_create)
        db.session.commit()
        login_user(user_to_create)
        flash(f'Account created successfully! You are now logged as {user_to_create.username}', category='success')
        return redirect(url_for('main.home_page'))
    if form.errors != {}:  # if there ara not errors from the validations
        for err_msg in form.errors.values():
            flash(f'{err_msg}', category='danger')
    return render_template('user_templates/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():

        attempted_user = User.query.filter_by(username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(attempted_password=form.password.data):

            login_user(attempted_user)

            flash(f'Success! You are logged in as {attempted_user.username}', category='success')
            return redirect(url_for('main.article_page'))
        else:
            flash('Username and password are not match! Please try again', category='danger')

    return render_template('user_templates/login.html', form=form)


@users.route('/logout')
def logout_page():
    logout_user()
    flash("You have been log out!", category='info')
    return redirect(url_for('main.home_page'))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/images', picture_fn)
    form_picture.save(picture_path)
    return picture_fn


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateProfileForm()
    posts = current_user.posts

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='images/' + current_user.image_file)

    return render_template('user_templates/profile.html', title='Account', image_file=image_file, form=form, posts=posts)


@users.route("/user/<string:username>")
@login_required
def username_page(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('post_templates/user_posts.html', posts=posts, user=user)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='noreply@techblog.com', recipients=[user])
    msg.body = '''If y

    '''


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('account'))

    form = ResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password', 'info')
        return redirect(url_for('login_page'))
    return render_template('user_templates/reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('account'))
    user = User.verify_reset_token(token)

    if user is None:
        flash('That is invalid or expired link', 'warning')
        return redirect(url_for('reset_request'))

    form = ResetPasswordForm()

    return render_template('user_templates/reset_token.html', title='Reset Password', form=form)

blog/templates/articles.html
{% extends 'based.html' %}

{% block title %}
<title>Articles</title>
{% endblock %}

{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="" class="rounded-circle article-img" >
            <div class="media-body">
                <div class="article-metadata">
                     <a class="mr-2 text-muted" href="{{ url_for('users.username_page', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content }}</p>
            </div>
        </article>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a href="{{ url_for('main.article_page', page=page_num)}}" class="btn btn-info mb-4">{{ page_num }}</a>
                    {% else %}
                    <a href="{{ url_for('main.article_page', page=page_num)}}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
                    {% endif %}
            {% else %}
            {% endif %}
            {% endfor %}

{% endblock %}

blog/templates/based.html
<!doctype html>
<html lang="en">
   <head>
      <!-- Required meta tags -->
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://pyscript.net/alpha/pyscript.css" />
<script defer src="https://pyscript.net/alpha/pyscript.js"></script>
      <!-- Bootstrap CSS -->
      <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
      <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

      {% block title %}
      <title>Tech blog</title>
      {% endblock %}
   </head>
   <body>
      <header class="site-header">
         <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
            <div class="container">
               <a class="navbar-brand" href="{{ url_for('main.article_page') }}">&lt;TECH BLOG&gt;</a>
               <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
               <span class="navbar-toggler-icon"></span>
               </button>
             {% if current_user.is_authenticated %}
               <div class="collapse navbar-collapse" id="navbarNav">
                  <ul class="navbar-nav mr-auto">
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.article_page') }}">Posts</a>
                     </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('groups.groups_page') }}">Groups</a>
                     </li>
                      <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('main.python_repl') }}">Code Yourself</a>
                     </li>
                  </ul>
               </div>

            {% endif %}
               <div>
                  {% if current_user.is_authenticated %}
                  <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('posts.new_post') }}">New Post</a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link active" href="{{ url_for('users.account') }}">
                        <i class="fa-brands fa-grav"></i>
                        {{ current_user.username }}
                        </a>
                     </li>
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('users.logout_page') }}">&lt;/Logout&gt;</a>
                     </li>
                  </ul>
                  {%  else %}
                  <ul class="navbar-nav">
                     <li class="nav-item">
                        <a class="nav-link active" aria-current="page" href="{{ url_for('users.login_page') }}">
                        <i class="fa-regular fa-circle-user"></i>
                        </a>
                     </li>
                  </ul>
                  {% endif %}
               </div>
            </div>
         </nav>
         <div>
         </div>
      </header>
      <main role="main" class="container">
         <div class="row">
            <div class="col-md-8">
               {%   with messages = get_flashed_messages(with_categories=true) %}
               {%  if messages %}
               {% for category, message in messages %}
               <div class="alert alert-{{ category }} alert-dismissible fade show">
                  {{ message }}
                  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
               </div>
               {% endfor %}
               {% endif %}
               {% endwith %}
                {% block content %} {% endblock %}
            </div>
            <div class="col-md-4">
                <div class="content-section">
                    <h3>Our Sidebar</h3>
                    <p class="text-muted">You can put any information here you'd like.
                        <ul>
                            <li class="list-group-item list-group-item-light">Latest Posts</li>
                            <li class="list-group-item list-group-item-light">Announcements</li>
                            <li class="list-group-item list-group-item-light">Calendars</li>
                            <li class="list-group-item list-group-item-light">etc</li>
                        </ul>
                    </p>
                </div>
            </div>
         </div>
      </main>
      <!-- Optional JavaScript; choose one of the two! -->
      <script src="https://kit.fontawesome.com/09084a4dd4.js" crossorigin="anonymous"></script>
      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
   </body>


    <footer class="site-footer">


    </footer>

</html>

blog/templates/home.html
{%  extends 'based.html' %}

{%  block title %}
<title>Home</title>
{%  endblock %}


{%  block content %}
    <div class="position-relative overflow-hidden p-3 p-md-5 m-md-3 text-center bg-light" style="color: white">
        <div class="col-md-5 p-lg-5 mx-auto my-5">

            <h1 class="display-4 font-weight-normal">
                    Tech Blog
            </h1>
            <p class="lead font-weight-normal">Start writing your articles</p>
            <a href="{{ url_for('main.article_page')}}" class="btn btn-primary">Get Started</a>
        </div>
        <div class="product-device box-shadow d-none d-md-block"></div>
        <div class="product-device product-device-2 box-shadow d-none d-md-block"></div>
    </div>
{% endblock %}