blog/posts/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, TextAreaField
from wtforms.validators import Length, EqualTo, Email, DataRequired, ValidationError


class PostForm(FlaskForm):
    title = StringField('Title', validators=[DataRequired()])
    content = TextAreaField('Content', validators=[DataRequired()])
    submit = SubmitField('Post')


class SearchForm(FlaskForm):
    search = StringField('Search', validators=[DataRequired()])
    submit = SubmitField('submit')

blog/posts/routes.py
from flask import Blueprint
from flask import render_template, redirect, url_for, flash, abort, request

from blog.posts.forms import PostForm, SearchForm
from blog.models import Post
from blog import db
from flask_login import login_required, current_user

posts = Blueprint('posts', __name__)


@posts.route('/post/new', methods=['GET', 'POST'])
@login_required
def new_post():
    form = PostForm()
    if form.validate_on_submit():
        flash('Your post has been created', 'success')
        post = Post(title=form.title.data, content=form.content.data, owner=current_user.id)
        db.session.add(post)
        db.session.commit()
        return redirect(url_for('main.article_page'))
    return render_template('post_templates/create_post.html', title='New Post', form=form, legend='New Post')


@posts.route('/post/<int:post_id>')
def post(post_id):
    post = Post.query.get_or_404(post_id)
    return render_template('post_templates/post.html', title=post.title, post=post)


@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def post_update(post_id):
    post = Post.query.get_or_404(post_id)
    form = PostForm()
    if post.author != current_user:
        abort(403)

    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        db.session.commit()
        flash('You post has been updated', 'success')
        return redirect(url_for('posts.post', post_id=post.id))
    elif request.method == 'GET':
        form.title.data = post.title
        form.content.data = post.content
    return render_template('post_templates/create_post.html', title='Update Post', form=form, legend='Update post')


@posts.route('/post/search', methods=['POST'])
@login_required
def search_engine():
    form = SearchForm()

    if form.validate_on_submit():
        # post_searched = form.searched.data
        page = request.args.get('page', 1, type=int)
        posts1 = Post.query.order_by(Post.date_posted.desc()).paginate(page=page, per_page=5)
        return render_template('post_templates/articles.html', posts=posts1)


@posts.route('/post/<int:post_id>/delete', methods=['POST'])
@login_required
def post_delete(post_id):
    post1 = Post.query.get_or_404(post_id)
    if post1.author != current_user:
        abort(403)

    db.session.delete(post1)
    db.session.commit()
    flash('You post has been deleted', 'success')

    return redirect(url_for('main.article_page'))

blog/users/routes.py
from flask import Flask, render_template, redirect, url_for, flash, request

from blog.users.forms import RegisterForm, LoginForm, UpdateProfileForm, ResetForm, ResetPasswordForm
from blog.models import User, Post
from blog import db
from flask_login import login_user, logout_user, login_required, current_user
import secrets
import os
from flask_mail import Message
from flask import Blueprint, current_app

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(username=form.username.data, email=form.email.data, passwordHash=form.password1.data)
        db.session.add(user_to_create)
        db.session.commit()
        login_user(user_to_create)
        flash(f'Account created successfully! You are now logged as {user_to_create.username}', category='success')
        return redirect(url_for('main.home_page'))
    if form.errors != {}:  # if there ara not errors from the validations
        for err_msg in form.errors.values():
            flash(f'{err_msg}', category='danger')
    return render_template('user_templates/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():

        attempted_user = User.query.filter_by(username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(attempted_password=form.password.data):

            login_user(attempted_user)

            flash(f'Success! You are logged in as {attempted_user.username}', category='success')
            return redirect(url_for('main.article_page'))
        else:
            flash('Username and password are not match! Please try again', category='danger')

    return render_template('user_templates/login.html', form=form)


@users.route('/logout')
def logout_page():
    logout_user()
    flash("You have been log out!", category='info')
    return redirect(url_for('main.home_page'))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/images', picture_fn)
    form_picture.save(picture_path)
    return picture_fn


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateProfileForm()
    posts = current_user.posts

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='images/' + current_user.image_file)

    return render_template('user_templates/profile.html', title='Account', image_file=image_file, form=form, posts=posts)


@users.route("/user/<string:username>")
@login_required
def username_page(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('post_templates/user_posts.html', posts=posts, user=user)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='noreply@techblog.com', recipients=[user])
    msg.body = '''If y

    '''


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('account'))

    form = ResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password', 'info')
        return redirect(url_for('login_page'))
    return render_template('user_templates/reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('account'))
    user = User.verify_reset_token(token)

    if user is None:
        flash('That is invalid or expired link', 'warning')
        return redirect(url_for('reset_request'))

    form = ResetPasswordForm()

    return render_template('user_templates/reset_token.html', title='Reset Password', form=form)

blog/templates/post_templates/articles.html
{% extends 'based.html' %}

{% block title %}
<title>Articles</title>
{% endblock %}



{% block content %}

   <nav class="navbar bg-light">
  <div class="container-fluid" style="padding-left: 350px">
    <form class="d-flex" role="search" method="POST" action="{{ url_for('posts.search_engine') }}" >
        {{ form.hidden_tag() }}
      <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>
  </div>
</nav>
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="" class="rounded-circle article-img" >
            <div class="media-body">
                <div class="article-metadata">
                     <a class="mr-2 text-muted" href="{{ url_for('users.username_page', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content }}</p>
            </div>
        </article>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a href="{{ url_for('main.article_page', page=page_num)}}" class="btn btn-info mb-4">{{ page_num }}</a>
                    {% else %}
                    <a href="{{ url_for('main.article_page', page=page_num)}}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
                    {% endif %}
            {% else %}
            {% endif %}
            {% endfor %}

{% endblock %}

blog/templates/post_templates/create_post.html
{% extends 'based.html' %}

{% block title %}
<title>New Post</title>
{% endblock %}


{%  block content %}
  <div class="content-section">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="form-group">
            <legend class="border-bottom mb-4">{{ legend }}</legend>
            <div class="form-group">
                {{ form.title.label(class="form-control-label") }}
                {% if form.title.errors %}
                    {{ form.title(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.title.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.title(class="form-control form-control-lg") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.content.label(class="form-control-label") }}
                {% if form.content.errors %}
                    {{ form.content(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.content.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.content(class="form-control form-control-lg", placeholder="Maximum 5000 signs") }}
                {% endif %}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
</div>
{% endblock %}

blog/templates/post_templates/post.html
{% extends 'based.html' %}

{% block title %}
<title>Articles</title>
{% endblock %}

{% block content %}

        <article class="media content-section">
{#            <img src="{{ url_for('web/static', filena) }}" alt="" class="rounded-circle article-img">#}
            <div class="media-body">
                <div class="article-metadata">
                    <h3>{{ post.owner.username}}</h3>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                        </div>
                             <h2 class="article-title"> {{ post.title }}</h2>
                            <p class="article-content"> {{ post.content }}</p>
                        </div>
                        {% if post.author.id == current_user.id%}
                        <div>
                            <a class="btn btn-secondary btn-sm m-1 pl-3"  href={{url_for('posts.post_update',post_id=post.id)}}>Update</a>

                            <button type="button" class="btn btn-danger btn-sm m-1" data-bs-toggle="modal" data-bs-target="#deleteModal">Delete</button>
                        </div>
                    {% endif %}
        </article>

         <!-- Modal -->
  <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="deleteModalLabel">Delete Post?</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <form action="{{ url_for('posts.post_delete', post_id=post.id) }}" method="POST">
            <input class="btn btn-danger" type="submit" value="Delete">
          </form>
        </div>
      </div>
    </div>
  </div>

{% endblock %}

blog/templates/post_templates/user_posts.html
{% extends 'based.html' %}

{% block title %}
<title>Articles</title>
{% endblock %}

<h1 class="mb-3">Posts by {{ user.username }} ({{ posts.total }})</h1>
{% block content %}
    {% for post in posts.items %}
        <article class="media content-section">
            <img src="{{ url_for('static', filename='images/' + post.author.image_file) }}" alt="" class="rounded-circle article-img">
            <div class="media-body">
                <div class="article-metadata">
                     <a class="mr-2" href="{{ url_for('users.username_page', username=post.author.username) }}">{{ post.author.username }}</a>
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content }}</p>
            </div>
        </article>
        {% endfor %}
        {% for page_num in posts.iter_pages(left_edge=1, right_edge=1,left_current=1,right_current=2) %}
            {% if page_num %}
                {% if posts.page == page_num %}
                    <a href="{{ url_for('users.username_page', username=user.username)}}" class="btn btn-info mb-4">{{ page_num }}</a>
                    {% else %}
                    <a href="{{ url_for('users.username_page', username=user.username)}}" class="btn btn-outline-info mb-4">{{ page_num }}</a>
                    {% endif %}
            {% else %}
            {% endif %}
            {% endfor %}

{% endblock %}