blog/users/routes.py
from flask import Flask, render_template, redirect, url_for, flash, request

from blog.users.forms import RegisterForm, LoginForm, UpdateProfileForm, ResetForm, ResetPasswordForm
from blog.models import User, Post
from blog import db
from flask_login import login_user, logout_user, login_required, current_user
import secrets
import os
from flask_mail import Message
from flask import Blueprint, current_app

users = Blueprint('users', __name__)


@users.route('/register', methods=['GET', 'POST'])
def register_page():
    form = RegisterForm()
    if form.validate_on_submit():
        user_to_create = User(username=form.username.data, email=form.email.data, passwordHash=form.password1.data)
        db.session.add(user_to_create)
        db.session.commit()
        login_user(user_to_create)
        flash(f'Account created successfully! You are now logged as {user_to_create.username}', category='success')
        return redirect(url_for('main.home_page'))
    if form.errors != {}:  # if there ara not errors from the validations
        for err_msg in form.errors.values():
            flash(f'{err_msg}', category='danger')
    return render_template('user_templates/register.html', form=form)


@users.route('/login', methods=['GET', 'POST'])
def login_page():
    form = LoginForm()
    if form.validate_on_submit():

        attempted_user = User.query.filter_by(username=form.username.data).first()
        if attempted_user and attempted_user.check_password_correction(attempted_password=form.password.data):

            login_user(attempted_user)

            flash(f'Success! You are logged in as {attempted_user.username}', category='success')
            return redirect(url_for('main.article_page'))
        else:
            flash('Username and password are not match! Please try again', category='danger')

    return render_template('user_templates/login.html', form=form)


@users.route('/logout')
def logout_page():
    logout_user()
    flash("You have been log out!", category='info')
    return redirect(url_for('main.home_page'))


def save_picture(form_picture):
    random_hex = secrets.token_hex(8)
    _, f_ext = os.path.splitext(form_picture.filename)
    picture_fn = random_hex + f_ext
    picture_path = os.path.join(current_app.root_path, 'static/images', picture_fn)
    form_picture.save(picture_path)
    return picture_fn


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateProfileForm()
    posts = current_user.posts

    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated', 'success')
        return redirect(url_for('account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email

    image_file = url_for('static', filename='images/' + current_user.image_file)

    return render_template('user_templates/profile.html', title='Account', image_file=image_file, form=form, posts=posts)


@users.route("/user/<string:username>")
@login_required
def username_page(username):
    page = request.args.get('page', 1, type=int)
    user = User.query.filter_by(username=username).first_or_404()
    posts = Post.query.filter_by(author=user) \
        .order_by(Post.date_posted.desc()) \
        .paginate(page=page, per_page=5)
    return render_template('post_templates/user_posts.html', posts=posts, user=user)


def send_reset_email(user):
    token = user.get_reset_token()
    msg = Message('Password Reset Request', sender='noreply@techblog.com', recipients=[user])
    msg.body = '''If y

    '''


@users.route('/reset_password', methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('account'))

    form = ResetForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent to reset your password', 'info')
        return redirect(url_for('login_page'))
    return render_template('user_templates/reset_request.html', title='Reset Password', form=form)


@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('account'))
    user = User.verify_reset_token(token)

    if user is None:
        flash('That is invalid or expired link', 'warning')
        return redirect(url_for('reset_request'))

    form = ResetPasswordForm()

    return render_template('user_templates/reset_token.html', title='Reset Password', form=form)

blog/templates/user_templates/login.html
{% extends 'based.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}


{% block content %}
    <body class="text-center">
        <div class="container">
            <form action="" method="POST" class="form-signin" style="color:white">
                {{ form.hidden_tag() }}
                <p><img src="/blog/static/logo.png" alt=""></p>
                <br>
                <h1 class="h3 mb-3 font-weight-normal">
                    Please Login
                </h1>
                <br>
                {{ form.username.label() }}
                {{ form.username(class="form-control", placeholder="Username") }}

                {{ form.password.label() }}
                {{ form.password(class="form-control", placeholder="Password") }}
                <br>
                 <div class="checkbox mb-3">

                    <a href="{{ url_for("users.reset_request")}}" class="link-secondary">forgot password?</a>
                </div>
                <div class="checkbox mb-3">

                    <a href="{{ url_for("users.register_page")}}" class="link-secondary">Do not have an account?</a>
                </div>
                <br>
                {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            </form>
        </div>

    </body>
{% endblock %}

blog/templates/user_templates/profile.html
{%  extends 'based.html' %}

{%  block content %}

    <div class="content-section">
        <div class="media">
            <img class="rounded-circle account-img" src="{{ image_file }}" alt="">
            <div class="media-body">
                <h2 class="account-heading">{{ current_user.username }}</h2>
                <p class="text-secondary">{{ current_user.email }}</p>
            </div>
        </div>
     <form method="POST" action="" enctype="multipart/form-data">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Account Info</legend>
                <div class="form-group">
                    {{ form.username.label(class="form-control-label") }}

                    {% if form.username.errors %}
                        {{ form.username(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.username.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.username(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
                <div class="form-group">
                    {{ form.picture.label() }}
                    {{ form.picture(class="form-control-file") }}
                    {% if form.picture.errors %}
                        {% for error in form.picture.errors %}
                            <span class="text-danger">{{ error }}</span></br>
                        {% endfor %}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group">
                {{ form.submit(class="btn btn-outline-info") }}
            </div>
        </form>
        <br>
        <br>
        {% for post in posts %}
        <article class="media content-section">

            <div class="media-body">
                <div class="article-metadata">
                    <small class="text-muted">{{ post.date_posted.strftime('%Y-%m-%d') }}</small>
                </div>
                <h2><a href="{{ url_for('posts.post', post_id=post.id) }}" class="article-title"> {{ post.title }}</a></h2>
                <p class="article-content"> {{ post.content }}</p>
            </div>
        </article>
    {%  endfor %}
    </div>

{% endblock %}

blog/templates/user_templates/register.html
{% extends 'based.html' %}

{% block title %}
    <title>Register</title>
{% endblock %}


{% block content %}
    <body class="text-center">
        <div class="container">
            <form method="POST" class="form-register" action="" style="color:white;">
                {{ form.hidden_tag() }}
                <img src="../static/logo.png" alt="">
                <br>
                <h1 class="h3 mb-3 font-weight-normal">
                    Please Create your Account
                </h1>
                {{ form.username.label() }}
                {{ form.username(class="form-control",placeholder="username") }}

                {{ form.email.label() }}
                {{ form.email(class="form-control",placeholder="email") }}

                {{ form.password1.label() }}
                {{ form.password1(class="form-control",placeholder="password") }}

                {{ form.password2.label() }}
                {{ form.password2(class="form-control",placeholder="again password") }}

                 <div class="checkbox mb-3">

                    <a href="{{ url_for("users.login_page")}}" class="link-secondary">Already have an account?</a>
                </div>
                <br>
                {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
        </form>
     </div>
    </body>
{% endblock %}

blog/templates/user_templates/reset_request.html
{% extends 'based.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}


{% block content %}
    <body class="text-center">
        <div class="container">
            <form action="" method="POST" class="form-signin" style="color:white">
                {{ form.hidden_tag() }}
                <p><img src="/blog/static/logo.png" alt=""></p>
                <br>
                <h1 class="h3 mb-3 font-weight-normal">
                    What is your email address?
                </h1>
                <br>
                {{ form.email.label() }}
                {{ form.email(class="form-control", placeholder="Email address") }}

                <br>
                {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            </form>
        </div>

    </body>
{% endblock %}

blog/templates/user_templates/reset_token.html
{% extends 'based.html' %}

{% block title %}
    <title>Login</title>
{% endblock %}


{% block content %}
    <body class="text-center">
        <div class="container">
            <form action="" method="POST" class="form-signin" style="color:white">
                {{ form.hidden_tag() }}
                <p><img src="/blog/static/logo.png" alt=""></p>
                <br>
                <h1 class="h3 mb-3 font-weight-normal">

                </h1>
                <br>
                {{ form.password.label() }}
                {{ form.password(class="form-control", placeholder="Password") }}

                {{ form.password1.label() }}
                {{ form.password1(class="form-control", placeholder="Confirm Password") }}

                <br>
                {{ form.submit(class="btn btn-lg btn-block btn-primary") }}
            </form>
        </div>

    </body>
{% endblock %}